name: 07 - Expressions
on: 
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "[Debug] Print start-up data"
              if: ${{ inputs.debug }} == true
              run: |
                echo "Triggered by: ${{ github.actor }}"
                echo "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS: ${{ runner.os }}"
            - name: "[Debug] Print when triggered from main"
              if: ${{ inputs.debug }} == true and github.ref == 'refs/heads/main'
              run: |
                echo "This workflow was triggered from the main branch"
            - name: Greeting
              run: echo "Hell of World"