name: 08 - Using Variables
on: 
    push:
    workflow_dispatch:

env:
    WORKFLOW_VAR: "I am a workflow env var"
    OVERWRITTEN_VAR: "I will be overwritten"

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "I am a job env var"
            OVERWRITTEN_VAR: "I will be overwritten at the job level"
        steps:
            - name: Print Env Variables
              env:
                STEP_VAR: "I am a step env var"
                STEP_VAR2: "I am another step var"
              run: |
                echo "Step env var: ${{ env.STEP_VAR }}"
                echo "Step var env 2: ${{ env.STEP_VAR2 }}"
                echo "Job env var: ${{ env.JOB_VAR }}"
                echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
                echo "Overwritten var: ${{ env.OVERWRITTEN_VAR }}"
            - name: Overwritten Job Variable
              env:
                OVERWRITTEN_VAR: "I will be overwritten at the step level"
              run: |
                echo "Step env var: ${{ env.OVERWRITTEN_VAR }}"
                