name: 10 - Controlling the Execution Flow

on: 
    #push:
    workflow_dispatch:
        inputs:
            pass-units-tests:
                type: boolean
                description: Whether unit tests will pass or not
                default: false

jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: Lint and build
              run: echo "Linting and building project"
    unit-tests:
        runs-on: ubuntu-latest
        #continue-on-error: true #This will allow the workflow to continue even if this job fails when uncommented
        steps:
            - name: Running unit tests
              run: echo "Running unit tests"
            - name: Failing tests
              #Can also use IF at this level to condition the run
              run: |
                if [ ${{ inputs.pass-units-tests }} = false ]; then
                    echo "Failing tests"
                    exit 1
                fi
    deploy-nonprod:
        runs-on: ubuntu-latest
        needs: 
            - lint-build
            - unit-tests
        steps:
            - name: Deploy to non-prod
              run: echo "Deploying to non-prod"
    e2e-tests:
        runs-on: ubuntu-latest
        needs: deploy-nonprod
        steps:
            - name: Running end-to-end tests
              run: echo "Running end-to-end tests"
    load-tests:
        runs-on: ubuntu-latest
        needs: deploy-nonprod
        steps:
            - name: Running load tests
              run: echo "Running load tests"
    deploy-prod:
        runs-on: ubuntu-latest
        needs: 
            - e2e-tests
            - load-tests
        steps:
            - name: Deploy to prod
              run: echo "Deploying to prod"