name: 13 - Using Caching

on: 
    #push:
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                default: true
                description: Whether to execute cache step
            node-version:
                type: choice
                default: 20.x
                options:
                    - 18.x
                    - 19.x
                    - 20.x
                description: Node.js version to use

jobs:
    cache:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/react-app
        steps:
            # 1 We need to checkout code whenever we need to interact with our repository
            # 2 Install dependecies
            # 3 linting (not used here), formatting (not used here), unit testing, building
            # 4 Deploy to a nonprod environment
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  #node-version: '20.x'
                  node-version: ${{ inputs.node-version }}
            - name: Install dependencies
              run: npm ci
              #working-directory: 13-caching/react-app
            - name: Testing
              run: npm run test
              #working-directory: 13-caching/react-app
            - name: Building
              run: npm run build
            - name: Deploying to nonprod
              run: echo "Deploying to non-prod"